project:
  type: website

website:
  title: "Udeshi Salgado"
  site-url: "https://udeshisalgado.github.io"
  open-graph: true
  page-footer: "Made with ❤️ using [Quarto](https://quarto.org)"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Talks
        href: talks.qmd
      - icon: github
        href: https://github.com/udeshisalgado
      - icon: linkedin
        href: https://www.linkedin.com/in/udeshi-salgado/
      - text: Cardiff
        href: https://profiles.cardiff.ac.uk/research-staff/salgadomu

format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: "monospace"
    fontsize: 20px
    backgroundcolor: "#eeffee"
    fontcolor: "darkgreen"
    linkcolor: "black"
